### ISSUE TITLE
Endpoints are not reachable via localhost

### ISSUE THREAD

**Issue by sed-i** [canonical/cos-lite-bundle#45]
### Bug Description

COS lite charms use ingress, and are reachable via the proxied endpoint
```
curl http://pd-ssd-4cpu-8gb.us-central1-a.c.lma-light-load-testing.internal:80/cos-lite-load-test-prometheus-0/metrics
```

but not via localhost
```
$ curl http://localhost/cos-lite-load-test-prometheus-0/metrics
curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused
```

Seems like they all should be reachable via localhost too?

### To Reproduce

Deploy the bundle and try `curl http://localhost/cos-lite-load-test-prometheus-0/metrics`.

### Environment

Bundle from edge.

### Relevant log output

```shell
$ curl http://localhost/cos-lite-load-test-prometheus-0/metrics
curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused
```

**Comment by simskij** [comment]
This is the expected behavior. Traefik matches ingress paths using the provided hostname, and as `localhost` is not equal to `http://pd-ssd-4cpu-8gb.us-central1-a.c.lma-light-load-testing.internal`, it will not match. If your attempt is from **within** the Prometheus container, it should work assuming you also specify the Prometheus port (as port 80 only applies to the traefik route).
